# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'down.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 477)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.icon = QtWidgets.QToolButton(self.frame_3)
        self.icon.setStyleSheet("QToolButton {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    border: none;\n"
"    background: none;\n"
"}")
        self.icon.setText("")
        self.icon.setIconSize(QtCore.QSize(100, 100))
        self.icon.setAutoRaise(True)
        self.icon.setObjectName("icon")
        self.gridLayout_4.addWidget(self.icon, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.data = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data.setFont(font)
        self.data.setText("")
        self.data.setScaledContents(True)
        self.data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.data.setOpenExternalLinks(True)
        self.data.setObjectName("data")
        self.gridLayout_4.addWidget(self.data, 0, 1, 3, 2)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 2)
        self.progress_bar = QtWidgets.QProgressBar(Form)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 3, 0, 1, 2)
        self.screenshot = QtWidgets.QLabel(Form)
        self.screenshot.setText("")
        # self.screenshot.setScaledContents(False)
        self.screenshot.setAlignment(QtCore.Qt.AlignCenter)
        self.screenshot.setObjectName("screenshot")
        self.screenshot.setAcceptDrops(True)
        self.gridLayout.addWidget(self.screenshot, 0, 0, 1, 2)
        self.btn_install = QtWidgets.QPushButton(Form)
        self.btn_install.setObjectName("btn_install")
        self.gridLayout.addWidget(self.btn_install, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)

        self.screenshot.setScaledContents(True)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.progress_bar.setFormat(_translate("Form", "%p%"))
        self.btn_install.setText(_translate("Form", "Install"))
