# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'path_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(476, 49)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_icon = QtWidgets.QToolButton(Form)
        self.btn_icon.setText("")
        self.btn_icon.setIconSize(QtCore.QSize(25, 25))
        self.btn_icon.setAutoRaise(True)
        self.btn_icon.setObjectName("btn_icon")
        self.gridLayout.addWidget(self.btn_icon, 0, 0, 1, 1)
        self.line_path = QtWidgets.QLineEdit(Form)
        self.line_path.setStyleSheet("padding: 7px;\n"
"border-radius: 5px;")
        self.line_path.setFrame(False)
        self.line_path.setObjectName("line_path")
        self.gridLayout.addWidget(self.line_path, 0, 1, 1, 1)
        self.btn_browser = QtWidgets.QToolButton(Form)
        self.btn_browser.setText("")
        self.btn_browser.setIconSize(QtCore.QSize(25, 25))
        self.btn_browser.setAutoRaise(True)
        self.btn_browser.setObjectName("btn_browser")
        self.gridLayout.addWidget(self.btn_browser, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.line_path.setPlaceholderText(_translate("Form", "path to include"))
