# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/o_o/Projects/Ready/KANGAROO/kangaroo-app/src/ui/web.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 628)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.plugin_web_view = QtWebKitWidgets.QWebView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plugin_web_view.sizePolicy().hasHeightForWidth())
        self.plugin_web_view.setSizePolicy(sizePolicy)
        self.plugin_web_view.setUrl(QtCore.QUrl("about:blank"))
        self.plugin_web_view.setObjectName("plugin_web_view")
        self.gridLayout.addWidget(self.plugin_web_view, 0, 1, 1, 1)
        self.web_progress_bar = QtWidgets.QProgressBar(Form)
        self.web_progress_bar.setProperty("value", 24)
        self.web_progress_bar.setObjectName("web_progress_bar")
        self.gridLayout.addWidget(self.web_progress_bar, 1, 1, 1, 1)
        self.plugin_list_widget = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plugin_list_widget.sizePolicy().hasHeightForWidth())
        self.plugin_list_widget.setSizePolicy(sizePolicy)
        self.plugin_list_widget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plugin_list_widget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plugin_list_widget.setIconSize(QtCore.QSize(25, 25))
        self.plugin_list_widget.setProperty("isWrapping", False)
        self.plugin_list_widget.setGridSize(QtCore.QSize(45, 45))
        self.plugin_list_widget.setWordWrap(True)
        self.plugin_list_widget.setObjectName("plugin_list_widget")
        self.gridLayout.addWidget(self.plugin_list_widget, 0, 0, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from PyQt5 import QtWebKitWidgets
